export const CARD_NUMBER_MAX_LENGTH = 4;
export const CARD_EXPIRATION_DATE_MAX_LENGTH = 2;
export const CARD_CVC_MAX_LENGTH = 3;
export const CARD_PASSWORD_MAX_LENGTH = 1;
export const CARD_OWNER_NAME_MAX_LENGTH = 18;
